#!/usr/bin/env bash

# check dependencies
if ! command -v xcodebuild >/dev/null 2>&1; then
  echo "xcoverage needs xcodebuild to build coverage files"
  exit 1
fi

if ! command -v gcov >/dev/null 2>&1; then
  echo "xcoverage needs gcov to analyse coverage files"
  exit 1
fi
